# Generated by Django 2.2.9 on 2020-01-08 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitterfetch', '0002_tweet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tweet',
        ),
    ]
